// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketPal.DataAccess;

namespace TicketPal.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketPal.Domain.Entity.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EventEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("EventEntity");
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.PerformerEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ConcertEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<int?>("PerformerEntityId")
                        .HasColumnType("int");

                    b.Property<string>("PerformerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConcertEntityId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PerformerEntityId");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.TicketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("EventId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ActiveAccount")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveAccount = true,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas@example.com",
                            Firstname = "Lucas",
                            Lastname = "Castro",
                            Password = "$2a$11$W3rAdaU9MelpblF9OABROOfzei2G8KfzgGxXzXCnzKrIFPw8qDGsO",
                            Role = "ADMIN",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ActiveAccount = true,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ricardo@example.com",
                            Firstname = "Ricardo",
                            Lastname = "Poladura",
                            Password = "$2a$11$RBxv5cImlotXD5N.RR5ISe2.fCBwLjnlSikGX9qD6GqviYSuxz0Wy",
                            Role = "ADMIN",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ActiveAccount = true,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "spectator@example.com",
                            Firstname = "Spectator",
                            Lastname = "Test",
                            Password = "$2a$11$kW6OvNc663PJg1Roskzt7ODvuavB16wG/avSBcvq3sfj2XWochFb6",
                            Role = "SPECTATOR",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ActiveAccount = true,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "seller@example.com",
                            Firstname = "Seller",
                            Lastname = "Test",
                            Password = "$2a$11$bcMKfdGnGo.MBS9lyThTQOHcQa4KGKokKYCa8siiPdTH2fl3F0j7a",
                            Role = "SELLER",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ActiveAccount = true,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supervisor@example.com",
                            Firstname = "Supervisor",
                            Lastname = "Test",
                            Password = "$2a$11$xjmsbqpU05gKnLz7FoF5i.46.UWc3AecgdLHs3BaWW8UoFUd1XZha",
                            Role = "SUPERVISOR",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ActiveAccount = true,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "artist@example.com",
                            Firstname = "Artist",
                            Lastname = "Test",
                            Password = "$2a$11$ZPwITK9nGKED44d7kqrnwOWZn0ssh.VlXXxCqLfkZRsi.pdm2HjPW",
                            Role = "ARTIST",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.ConcertEntity", b =>
                {
                    b.HasBaseType("TicketPal.Domain.Entity.EventEntity");

                    b.Property<string>("TourName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ConcertEntity");
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.PerformerEntity", b =>
                {
                    b.HasOne("TicketPal.Domain.Entity.ConcertEntity", null)
                        .WithMany("Artists")
                        .HasForeignKey("ConcertEntityId");

                    b.HasOne("TicketPal.Domain.Entity.GenreEntity", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.HasOne("TicketPal.Domain.Entity.UserEntity", "UserInfo")
                        .WithOne("Performer")
                        .HasForeignKey("TicketPal.Domain.Entity.PerformerEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketPal.Domain.Entity.PerformerEntity", null)
                        .WithMany("Members")
                        .HasForeignKey("PerformerEntityId");

                    b.Navigation("Genre");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.TicketEntity", b =>
                {
                    b.HasOne("TicketPal.Domain.Entity.UserEntity", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId");

                    b.HasOne("TicketPal.Domain.Entity.EventEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.Navigation("Buyer");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.PerformerEntity", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.UserEntity", b =>
                {
                    b.Navigation("Performer");
                });

            modelBuilder.Entity("TicketPal.Domain.Entity.ConcertEntity", b =>
                {
                    b.Navigation("Artists");
                });
#pragma warning restore 612, 618
        }
    }
}
